from __future__ import annotations
from typing import Protocol


class FSPolicy(Protocol):
    def allow_root(self, root: str) -> None: ...
    def require_read(self, path: str) -> None: ...
    def require_write(self, path: str) -> None: ...
    def is_allowed(self, path: str) -> bool: ...
