# src/adaos/ports/git.py
from __future__ import annotations
from typing import Protocol, Optional, Sequence


class GitClient(Protocol):
    def ensure_repo(self, dir: str, url: str, branch: Optional[str] = None) -> None: ...
    def pull(self, dir: str) -> None: ...
    def current_commit(self, dir: str) -> str: ...

    # mono/sparse
    def sparse_init(self, dir: str, cone: bool = True) -> None: ...
    def sparse_set(self, dir: str, paths: Sequence[str], no_cone: bool = True) -> None: ...
    def sparse_add(self, dir: str, path: str) -> None: ...
