# src/adaos/ports/git.py
from __future__ import annotations
from typing import Protocol, Sequence, Optional, List


class GitClient(Protocol):
    def ensure_repo(self, dir: str, url: str, branch: Optional[str] = None) -> None: ...
    def pull(self, dir: str) -> None: ...
    def current_commit(self, dir: str) -> str: ...
    def sparse_init(self, dir: str, cone: bool = True) -> None: ...
    def sparse_set(self, dir: str, paths: Sequence[str], no_cone: bool = True) -> None: ...
    def sparse_add(self, dir: str, path: str) -> None: ...

    # NEW:
    def changed_files(self, dir: str, subpath: Optional[str] = None) -> List[str]: ...
    def commit_subpath(self, dir: str, subpath: str, message: str, author_name: str, author_email: str, signoff: bool = False) -> str: ...
    def push(self, dir: str, remote: str = "origin", branch: Optional[str] = None) -> None: ...
