from __future__ import annotations
from typing import Protocol, Sequence


class HeartbeatPort(Protocol):
    async def register(self, hub_url: str, token: str, *, node_id: str, subnet_id: str, hostname: str, roles: Sequence[str]) -> bool: ...
    async def heartbeat(self, hub_url: str, token: str, *, node_id: str) -> bool: ...
    async def deregister(self, hub_url: str, token: str, *, node_id: str) -> None: ...
