from __future__ import annotations
from typing import Protocol
from pathlib import Path


class PathProvider(Protocol):
    """src/adaos/adapters/fs/path_provider.py"""

    def base(self) -> Path: ...
    def skills_dir(self) -> str: ...
    def scenarios_dir(self) -> str: ...
    def state_dir(self) -> str: ...
    def cache_dir(self) -> str: ...
    def logs_dir(self) -> str: ...
