from __future__ import annotations
from typing import Protocol
from pathlib import Path


class PathProvider(Protocol):
    """Contract published by :mod:`adaos.adapters.fs.path_provider`."""

    @property
    def base(self) -> Path: ...

    @property
    def package_dir(self) -> Path: ...

    def base_dir(self) -> Path: ...
    def locales_dir(self) -> Path: ...
    def locales_base_dir(self) -> Path: ...
    def skills_locales_dir(self) -> Path: ...
    def scenarios_locales_dir(self) -> Path: ...
    def skill_templates_dir(self) -> Path: ...
    def scenario_templates_dir(self) -> Path: ...
    def skills_dir(self) -> Path: ...
    def scenarios_dir(self) -> Path: ...
    def models_dir(self) -> Path: ...
    def state_dir(self) -> Path: ...
    def cache_dir(self) -> Path: ...
    def logs_dir(self) -> Path: ...
    def tmp_dir(self) -> Path: ...
    
