from __future__ import annotations
from typing import Protocol


class PathProvider(Protocol):
    def base(self) -> str: ...
    def skills_dir(self) -> str: ...
    def scenarios_dir(self) -> str: ...
    def state_dir(self) -> str: ...
    def cache_dir(self) -> str: ...
    def logs_dir(self) -> str: ...
