from __future__ import annotations
from typing import Protocol, Iterable, Optional


class Capabilities(Protocol):
    def grant(self, subject: str, *caps: str) -> None: ...
    def revoke(self, subject: str, *caps: str) -> None: ...
    def has(self, subject: str, cap: str) -> bool: ...
    def require(self, subject: str, *caps: str) -> None: ...


class Net(Protocol):
    """src/adaos/services/policy/net.py"""

    def allow(self, *domains: str) -> None: ...
    def deny(self, *domains: str) -> None: ...
    def is_allowed_url(self, url: str) -> bool: ...
    def require_url(self, url: str) -> None: ...
