from __future__ import annotations
from typing import Protocol, Optional
from adaos.domain import SkillMeta  # метаданные сценария по сути аналогичны


class ScenarioRepository(Protocol):
    def ensure(self) -> None: ...
    def list(self) -> list[SkillMeta]: ...
    def get(self, scenario_id: str) -> Optional[SkillMeta]: ...
    def install(self, name: str, *, branch: Optional[str] = None, dest_name: Optional[str] = None) -> SkillMeta: ...
    def remove(self, scenario_id: str) -> None: ...
