# src/adaos/ports/skill_registry.py
from __future__ import annotations
from typing import Protocol, Optional, Iterable
from adaos.domain import SkillRecord


class SkillRegistry(Protocol):
    """from adaos.adapters.skills.git_repo"""

    def list(self) -> list[SkillRecord]: ...
    def get(self, name: str) -> Optional[SkillRecord]: ...
    def register(self, name: str, *, pin: str | None = None, active_version: str | None = None, repo_url: str | None = None) -> SkillRecord: ...
    def unregister(self, name: str) -> None: ...
    def set_all(self, records: Iterable[SkillRecord]) -> None: ...
