# src/adaos/ports/skills.py
from __future__ import annotations
from typing import Protocol, Optional
from adaos.domain import SkillMeta


class SkillRepository(Protocol):
    def ensure(self) -> None: ...
    def list(self) -> list[SkillMeta]: ...
    def get(self, skill_id: str) -> Optional[SkillMeta]: ...
    def install(self, url_or_name: str, *, branch: Optional[str] = None, dest_name: Optional[str] = None) -> SkillMeta: ...
    def uninstall(self, skill_id: str) -> None: ...
