from __future__ import annotations
from typing import Protocol, Any


class SubnetKVPort(Protocol):
    def is_hub(self) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> bool: ...
